menu:
    主页: /
    目录: /archives/
    下载: /download.html
    GitHub: https://github.com/actboy168/YDWE

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Copyright Infomation
startyear: 2014
